version: '3.1'
services:
  db:
    image: postgres:12-alpine
    container_name: ms_user_db
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: ms_user_app
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data: